services:
  - type: web
    name: ladico-comp3
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
